FROM public.ecr.aws/lambda/python:3.12

COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements-lambda.txt

COPY app ${LAMBDA_TASK_ROOT}/app

CMD ["app.lambdas.fetcher_handler.lambda_handler"]
